export const REMOVE_FROM_CART= 'REMOVE_FROM_CART'
export const ADD_TO_CART= 'ADD_TO_CART'
export const SET_SHIPPINGDATA='SET_SHIPPINGDATA'
export const CREATE_ORDER = 'CREATE_ORDER'
export const RESET_CART = 'RESET_CART'
export const MERCADOPAGO_PAYMENT = 'MERCADOPAGO_PAYMENT';
