export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_PRODUCT_BY_QUERY = 'GET_PRODUCT_BY_QUERY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CHANGE_ORDER = "CHANGE_ORDER";
